### ISSUE TITLE
BUG: Overlapping StatusCol ?? Plus some questions

### ISSUE THREAD

**Issue by ls-devs** [rasulomaroff/reactive.nvim#13]
Hi, I just installed `reactive` but it seems that there is an issue with `statuscol` , please see : 
![Sans titre](https://github.com/rasulomaroff/reactive.nvim/assets/58638832/4ddd2998-e923-4bcb-a532-a95e00b9ea1d)
![Sans titre_2](https://github.com/rasulomaroff/reactive.nvim/assets/58638832/cbb58e23-f62c-475c-ac7b-3f76572400d0)

Also note that when loading Neovim and interring a buffer, `relative` always start like I'm already in insert (green cursorline + green cursor).
When I switch mods, the cursor is staying with the color of the previous mod. Ex : I'm in insert mod : Cursor and CursorLine are green, I leave insert mode (back to normal) the cursorline change color but the cursor stay green. 
Can it be related to `noice` ?

Config : 
```lua 
return {
	"rasulomaroff/reactive.nvim",
	event = "BufReadPost",
	opts = {
		load = { "catppuccin-mocha-cursor", "catppuccin-mocha-cursorline" },
	},
}
```

**Comment by rasulomaroff** [comment]
Hi there @ls-devs! Regarding insert mode problem - it's not a reactive issue and as far as I remember it's a neovim issue that was fixed upstream. But you can try a temporary workaround (autocmd) from here #5, please let me know if that helped.

Regarding the `statuscol`. Could you please put additional lines in your config and tell me if that works?

try this:

```lua
opts = {
	load = { "catppuccin-mocha-cursor", "catppuccin-mocha-cursorline" },
	configs = {
		["catppuccin-mocha-cursorline"] = {
			modes = {
				i = {
					winhl = {
						CursorLineSign = { bg = "#ffffff" }
					}
				}
			}
		}
	}
}
```

I putted just a pure white color, but it's just to test that in the insert mode you'll see the white background for your cursor line sign columns.

I think I just forgot to highlight `CursorLineSign` group for `catppuccin` integration.

**Comment by rasulomaroff** [comment]
btw, just looking again at your screenshots, this can't be a `CursorLineSign` I guess, because it's on another side. Could you please clarify what plugin gives you those arrows? It seems not to be the `statuscol` option.

**Comment by ls-devs** [comment]
@rasulomaroff 
Hi,
The config you gave me for `reactive` gives this result : 
![image](https://github.com/rasulomaroff/reactive.nvim/assets/58638832/a4e31d93-3c03-49d4-86a7-8c7c1ce25ead)

The autocmd from #5 did not work for me the cursor is still the same color as the previous mode + it's still starting like I'm already in insert mode.  (like in the screenshot above).


> btw, just looking again at your screenshots, this can't be a `CursorLineSign` I guess, because it's on another side. Could you please clarify what plugin gives you those arrows?

I was talking about [statuscol.nvim](https://github.com/luukvbaal/statuscol.nvim), it's a plugin used with `ufo.nvim` ans this is what gives me those arrows (those are folds)

**Comment by rasulomaroff** [comment]
@ls-devs Yes, the result is expected because that sign column is on another side on your screenshot.

But actually I was thinking about another one. `CursorLineFold` - try this instead of `CursorLineSign` and it should work. If that works properly, I could update the `catppuccin` integration by including `CursorLineFold` group into that, but the problem is that in this case I'll need to include `CursorLineSign` group as well, because if I don't there will be a gap as on your screenshot because by default folds are on the very left position.

this is the default order if I remember it correctly
Fold - Sign - LineNumber

As I don't use these type of plugins, I never thought about this highlight group.

Regarding that insert mode problem. Is it only highlighted as if you're in insert mode or you're literally in insert mode? This problem was happening when using Telescope + Reactive together and the autocmd from that discussion usually solved it

**Comment by ls-devs** [comment]
@rasulomaroff `CursorLineFold` is what we looking for :)

For the insert mode problem, it's highlighted as if I'm in insert mode, but I'm actually in normal mode.
The autocmd do not solve the problem for me, unfortunately.
Please see the video : 

https://github.com/rasulomaroff/reactive.nvim/assets/58638832/e3340a75-3e8d-4b15-aeca-b9c2847f784d

**Comment by rasulomaroff** [comment]
@ls-devs if you could provide minimal repro, I would appreciate it
Because I don't know how I can reproduce this issue :(
If you disable noice, will the issue still persist?

**Comment by ls-devs** [comment]
@rasulomaroff Disabling `noice` does not change anything, the problem still persist.

I don't have any repro, and don't even know how to make one to be honest.

Maybe you can try my config that's located here : [https://github.com/ls-devs/nvim](ls-devs/nvim)

**Comment by rasulomaroff** [comment]
@ls-devs regarding `CursorLineFold` highlight group. I would recommend you to just link it to `CursorLineNr` for the modes you need it to. Because I think implementing that in catppuccin repo may be unnecessary as not everybody will like the result (area left to the line number will be highlighted as well), but I may be wrong? Maybe nobody really minds about it :D 

For repro you can try a simple trick - kinda binary disabling. Disable the first half of your plugins (except `reactive` of course). If the issue persists - disable another half of previously remained one and so on till you don't find the culprit. You get the idea

Anyway, I'll try to use your config as soon as I have time for that.

Btw, just checked it - it's even easier in your case since your lazy config has imported modules (ui, preview, lsp, gittools etc). Try disabling them one by one and find a module from where the issue starts.

**Comment by ls-devs** [comment]
@rasulomaroff Linking `CursorLineFold` to `CursorLineNr` definitly helps to solve a part of the issue. 
But I found out there's a problem with `git_signs` highlighting

With `git_signs` : 
![image](https://github.com/rasulomaroff/reactive.nvim/assets/58638832/098f2bfa-80e3-436c-8184-81621b88503e)

Without : 
![image](https://github.com/rasulomaroff/reactive.nvim/assets/58638832/7aab3dd0-5225-4c3d-af84-f6e9dfd34cb0)

For the insert mode problem, didn't found the real issue but manually pressing `Escape` before openning a file with `Telescope` solve the issue.

**Comment by rasulomaroff** [comment]
@ls-devs hi there! Yes telescope is very tricky with this. Especially when you just input the text, it changes modes for each keystroke. At least it did it when I was using it, maybe there's a special reason for that. 

But the key thing is that I never actually got that error, I just can't reproduce it at all (the one with insert mode)

If you just leave telescope and reactive, will the issue still persist? If so, can you send me your congifs of these plugins?

**Comment by ls-devs** [comment]
@rasulomaroff I tried disabling my plugins directories one by one. And I found that if I disable `ethanholz/nvim-lastplace` the issue is now gone.

**Comment by ls-devs** [comment]
I'll now close this issue since it's no more related to `reactive`. 
Thanks for all your help, love your plugin :)

**Comment by rasulomaroff** [comment]
@ls-devs as far as I can see the only purpose of `nvim-lastplace` is to get you back to place you were editing last in the file?

For that I just use a simple autocmd, which doesn't create those issues btw

take a look:

![Alacritty 2024-04-06 at 15-20](https://github.com/rasulomaroff/reactive.nvim/assets/80093436/9df83980-be6d-4e38-ae45-95ddab6ed0ba)

**Comment by ls-devs** [comment]
@rasulomaroff Yes so I decided to switch for an autocmd too.
This is the one I use : 
```lua
				{
					"BufWinEnter",
					function()
						local mark = vim.api.nvim_buf_get_mark(0, '"')
						local lcount = vim.api.nvim_buf_line_count(0)
						if mark[1] > 0 and mark[1] <= lcount then
							pcall(vim.api.nvim_win_set_cursor, 0, mark)
						end
					end,
					opts = {
						pattern = "*",
					},
					description = "Remember last place",
				},
```

Thanks for sharing, will try it :)
